core/urls.py
from django.conf.urls import url
from django.urls import path

from core import views

urlpatterns = [
    path('',views.index,name='index'),
]

digilearns/urls.py
from django.contrib import admin
from django.urls import path, include
from ussd.views import AfricasTalkingUssdGateway

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ussd/', AfricasTalkingUssdGateway.as_view(), name='africastalking_url'),
    path('', include(('frontend.urls', '') )),
    # path('', include('core.urls')),

]

frontend/urls.py
from django.conf.urls import include, url
from django.urls.base import reverse_lazy
from django.urls.conf import path

from frontend.views import user_login, dashboard, course_list, class_level_list, supervisor_list, module_list, \
    submodule_list, module_content_list, student_list, student_form, trivia_category_list, trivia_bank_list, \
    TriviaBankDeleteView, trivia_quiz_question_list, TriviaQuizQuestionDeleteView, ModuleContentDeleteView, \
    send_airtime_view, send_sms_view
from django.contrib.auth.views import auth_logout, logout_then_login


urlpatterns = [
    path('', dashboard, name='dashboard'),
    path('login', user_login, name='login'),
    path('logout',logout_then_login, name='logout'),

    url(r'^courses/(?P<pk>[0-9]+)?$',course_list, name='course_list'),
    url(r'^classes/(?P<pk>[0-9]+)?$',class_level_list, name='class_level_list'),
    url(r'^airtime/send$',send_airtime_view, name='send_airtime'),
    url(r'^sms/send$',send_sms_view, name='send_sms'),
    url(r'^trivia/categories/(?P<pk>[0-9]+)?$',trivia_category_list, name='triviaquiz_list'),
    url(r'^trivia/category/(?P<cat_id>[0-9]+)/bank/(?P<pk>[0-9]+)?$',trivia_bank_list, name='trivia_bank_list'),
    url(r'^trivia/category/bank/delete/(?P<cat_id>[0-9]+)/(?P<pk>[0-9]+)?$',TriviaBankDeleteView.as_view(), name='trivia_bank_delete'),
    url(r'^trivia/quiz/question/(?P<cat_id>[0-9]+)/(?P<pk>[0-9]+)?$',trivia_quiz_question_list, name='trivia_quiz_question_list'),
    url(r'^trivia/quiz/question/delete/(?P<cat_id>[0-9]+)/(?P<pk>[0-9]+)?$',TriviaQuizQuestionDeleteView.as_view(), name='trivia_quiz_question_delete'),
    url(r'^students$',student_list, name='student_list'),
    url(r'^students/add/(?P<pk>[0-9]+)?$',student_form, name='student_form'),
    url(r'^supervisors/(?P<pk>[0-9]+)?$',supervisor_list, name='supervisor_list'),
    url(r'^modules/(?P<course_id>[0-9]+)/(?P<pk>[0-9]+)?$',module_list, name='module_list'),
    url(r'^submodules/(?P<module_id>[0-9]+)/(?P<pk>[0-9]+)?$',submodule_list, name='submodule_list'),
    url(r'^module-contents/(?P<submodule_id>[0-9]+)/(?P<pk>[0-9]+)?$',module_content_list, name='module_content_list'),
    url(r'^module-contents/delete/(?P<submodule_id>[0-9]+)/(?P<pk>[0-9]+)?$',ModuleContentDeleteView.as_view(), name='module_content_delete'),
]

core/models.py
from decimal import Decimal

import jsonfield
from django.core.exceptions import ObjectDoesNotExist
from django.db import models


# Create your models here.


class BaseModel(models.Model):
    """
    Abstract model to be inherited by all other models
    """
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    is_deleted = models.BooleanField(default=False)

    class Meta:
        abstract = True


class GlobalConfig(models.Model):
    trivia_quiz_questions = models.PositiveIntegerField(default=10)
    prep_exam_questions = models.PositiveIntegerField(default=10)

    def __str__(self):
        return "Config set"

class State(models.Model):
    name = models.CharField(max_length=40, unique=True)
    capital = models.CharField(max_length=40)
    latitude = models.CharField(max_length=40, blank=True)
    longitude = models.CharField(max_length=40, blank=True)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name


class Language(BaseModel):
    """
    Language selection for the users
    """
    code = models.CharField(max_length=40)
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.code


class Classlevel(BaseModel):
    '''
    This modes defines the different classes offered by the app
    '''
    code = models.CharField(max_length=20, unique=True)
    name = models.CharField(max_length=20, null=True)

    def __str__(self):
        return self.name


class OrderField(models.PositiveIntegerField):

    def __init__(self, for_fields=None, *args, **kwargs):

        self.for_fields = for_fields
        super(OrderField, self).__init__(*args, **kwargs)

    def pre_save(self, model_instance, add):

        if getattr(model_instance, self.attname) is None:
            # no current value
            try:
                qs = self.model.objects.all()
                if self.for_fields:
                    # filter by objects with the same field values
                    # for the fields in "for_fields"
                    query = {field: getattr(model_instance, field) for
                             field in self.for_fields}
                    qs = qs.filter(**query)
                # get the order of the last item
                last_item = qs.latest(self.attname)
                value = last_item.order + 1
            except ObjectDoesNotExist:
                value = 0
            setattr(model_instance, self.attname, value)
            return value
        else:
            return super(OrderField, self).pre_save(model_instance, add)


class Supervisor(BaseModel):
    '''
    This model defines supervisor or teacher on the platform
    '''
    phone = models.CharField(max_length=15, unique=True)
    fullname = models.TextField()
    # token = models.CharField(max_length=10, default="0123456789")

    def __str__(self):
        return self.fullname


class Course(BaseModel):
    code = models.CharField(max_length=20, unique=True)
    title = models.CharField(max_length=120)
    class_level = models.ForeignKey(Classlevel, on_delete=models.CASCADE, related_name="learning_course_klass")
    supervisor = models.ForeignKey(Supervisor, on_delete=models.CASCADE, related_name="supervisor_for_course", null=True)

    def __str__(self):
        return "%s - %s" % (self.code,self.title)


class Module(BaseModel):
    title = models.CharField(max_length=2000)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    order = OrderField(blank=True, for_fields=['course'])

    class Meta:
        ordering = ['order']

    def __str__(self):
        return '{}. {}'.format(self.order, self.title)


class SubModule(BaseModel):
    title = models.CharField(max_length=2000)
    module = models.ForeignKey(Module, on_delete=models.CASCADE)
    order = OrderField(blank=True, for_fields=['module'])

    class Meta:
        ordering = ['order']

    def __str__(self):
        return '{}. {}'.format(self.order, self.title)


class ModuleContent(BaseModel):
    submodule = models.ForeignKey(SubModule, on_delete=models.CASCADE)
    content = models.TextField()
    order = OrderField(blank=True, for_fields=['submodule'])

    class Meta:
        ordering = ['order']

    def __str__(self):
        return '%s - %s - %s' % (self.order, self.submodule.title, self.content)



class Student(BaseModel):
    '''
    This model defines the properties of a student and also inherits from the User model
    '''
    phone = models.CharField(max_length=15, unique=True)
    first_name = models.CharField(max_length=120)
    last_name = models.CharField(max_length=120)
    dob = models.DateTimeField(null=True)
    parent_phone = models.CharField(max_length=15, null=True, blank=True)
    state = models.ForeignKey(State, on_delete=models.CASCADE, null=True)
    current_class = models.ForeignKey(Classlevel, on_delete=models.CASCADE, null=True)
    teacher = models.ForeignKey(Supervisor, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.fullname

    @property
    def fullname(self):
        return "%s %s" % (self.first_name, self.last_name)

    @property
    def courses(self):
        return Course.objects.filter(class_level=self.current_class)

    @property
    def state_name(self):
        return self.state.name


class StudentConfiguration(BaseModel):
    phone = models.CharField(max_length=20, unique=True)
    default_language = models.ForeignKey(Language, on_delete=models.CASCADE, null=True)
    state = models.ForeignKey(State, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.phone


log_type_choices = (
    ('content','content'),
    ('quiz','quiz'),
    ('exam','exam'),
)


class CourseProgress(BaseModel):
    # log_type = models.CharField(max_length=20, choices=log_type_choices)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    module = models.ForeignKey(Module, on_delete=models.CASCADE)
    submodule = models.ForeignKey(SubModule, on_delete=models.CASCADE)
    module_content = models.ForeignKey(ModuleContent, on_delete=models.CASCADE)
    is_module_completed = models.BooleanField(default=False)
    is_submodule_completed = models.BooleanField(default=False)
    is_quiz_completed = models.BooleanField(default=False)

    class Meta:
        unique_together = (('student','course','module','submodule','module_content'),)

    def __str__(self):
        return self.student.fullname


class Quiz(BaseModel):
    """
    Quiz , Exam or Test
    """
    module = models.ForeignKey(Module, on_delete=models.CASCADE, null=True) # May have topic or may not have
    name = models.CharField(max_length=1000)
    question_count = models.IntegerField(default=0)
    is_roll_out = models.BooleanField(default=False)

    class Meta:
        ordering = ['created', ]
        verbose_name_plural ="Quizzes"

    def __str__(self):
        return self.name

    @property
    def questions(self):
        return self.question_set.all()


class Question(BaseModel):
    """
    Each question object per Quiz. Question is meant to have options and choices
    """
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    label = models.CharField(max_length=1000)
    order = OrderField(blank=True, for_fields=['quiz'])

    class Meta:
        ordering = ['order']

    def __str__(self):
        return self.label

    @property
    def options(self):
        return self.answer_set.all()


class Answer(BaseModel):
    """
    This is for question answer choices. anad to mark those correct choice or choices
    """
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    text = models.CharField(max_length=1000)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return "%s - %s" % (self.question.label, self.text)


class QuizTaker(BaseModel):
    """
    This is to track student who attempted a quiz and the answers they chose for each question
    """
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    correct_answers = models.IntegerField(default=0)
    completed = models.BooleanField(default=False)

    def __str__(self):
        return self.student.fullname


class QuizTakerAnswer(BaseModel):
    """
    This is to track of what student chose in the quiz
    """
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        return "%s - %s - %s" % (self.student.fullname, self.question, self.answer)


class QuizProgress(BaseModel):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    class Meta:
        unique_together = (('student','quiz','question'),)

    def __str__(self):
        return self.student.fullname


class UserSession(BaseModel):
    """
    this class facilitates the creation of ussd interaction objects. Storing user sessions
    """
    session_id = models.CharField(max_length=100)
    phone = models.BigIntegerField()
    screens = jsonfield.JSONField()

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return u"%s %s %s" %  (self.session_id, self.phone, self.screens)


################## TRIVIA QUIZ ################################

class TriviaQuiz(BaseModel):
    """
    Trivia Quiz
    """
    name = models.CharField(max_length=1000)

    class Meta:
        ordering = ['created', ]
        verbose_name_plural ="Trivia Quizzes"

    def __str__(self):
        return self.name

    @property
    def questions(self):

frontend/models.py
from django.db import models

# Create your models here.

frontend/forms.py
from django import forms

from core.models import Course, Classlevel, Supervisor, Module, SubModule, ModuleContent, Student, Quiz, TriviaQuiz, \
    TriviaBank, TriviaQuestion, TriviaAnswer


class CourseForm(forms.ModelForm):

    class Meta:
        model = Course
        fields = ['code','title','class_level']

        widgets = {
            'code':forms.TextInput(attrs={'class':'form-control border-primary'}),
            'title':forms.TextInput(attrs={'class':'form-control border-primary'}),
            'class_level':forms.Select(attrs={'class':'form-control border-primary'}),
        }


class StudentForm(forms.ModelForm):

    class Meta:
        model = Student
        fields = ['first_name','last_name','phone','dob','parent_phone','state','current_class','teacher']

        widgets = {
            'first_name':forms.TextInput(attrs={'class':'form-control border-primary'}),
            'last_name':forms.TextInput(attrs={'class':'form-control border-primary'}),
            'phone':forms.TextInput(attrs={'class':'form-control border-primary'}),
            'dob':forms.TextInput(attrs={'class':'form-control border-primary'}),
            'parent_phone':forms.TextInput(attrs={'class':'form-control border-primary'}),
            'state': forms.Select(attrs={'class': 'form-control border-primary'}),
            'current_class': forms.Select(attrs={'class': 'form-control border-primary'}),
            'teacher': forms.Select(attrs={'class': 'form-control border-primary'}),
        }


class ClassLevelForm(forms.ModelForm):

    class Meta:
        model = Classlevel
        fields = ['code','name']

        widgets = {
            'code':forms.TextInput(attrs={'class':'form-control border-primary'}),
            'name':forms.TextInput(attrs={'class':'form-control border-primary'}),
        }


class SupervisorForm(forms.ModelForm):

    class Meta:
        model = Supervisor
        fields = ['phone','fullname']

        widgets = {
            'phone':forms.TextInput(attrs={'class':'form-control border-primary'}),
            'fullname':forms.TextInput(attrs={'class':'form-control border-primary'}),
        }


class ModuleForm(forms.ModelForm):

    class Meta:
        model = Module
        fields = ['title', 'order']

        widgets = {
            'title':forms.TextInput(attrs={'class':'form-control border-primary'}),
            'order':forms.TextInput(attrs={'class':'form-control border-primary'}),
            'course': forms.Select(attrs={'class': 'form-control border-primary'}),
        }


class SubModuleForm(forms.ModelForm):

    class Meta:
        model = SubModule
        fields = ['title', 'order']

        widgets = {
            'title':forms.TextInput(attrs={'class':'form-control border-primary'}),
            'order':forms.TextInput(attrs={'class':'form-control border-primary'}),
        }


class ModuleContentForm(forms.ModelForm):

    class Meta:
        model = ModuleContent
        fields = ['content', 'order']

        widgets = {
            'content':forms.Textarea(attrs={'class':'form-control border-primary'}),
            'order':forms.TextInput(attrs={'class':'form-control border-primary'}),
        }


class QuizForm(forms.ModelForm):

    class Meta:
        model = Quiz
        fields = ['name', 'module','is_roll_out']

        widgets = {
            'name':forms.Textarea(attrs={'class':'form-control border-primary'}),
            'module': forms.Select(attrs={'class': 'form-control border-primary'}),
        }


class TriviaQuizForm(forms.ModelForm):

    class Meta:
        model = TriviaQuiz
        fields = ['name',]

        widgets = {
            'name':forms.TextInput(attrs={'class':'form-control border-primary'}),
        }


class TriviaBankForm(forms.ModelForm):

    class Meta:
        model = TriviaBank
        fields = [ 'content', 'order',]

        widgets = {
            'order':forms.TextInput(attrs={'class':'form-control border-primary'}),
            'content': forms.Textarea(attrs={'class': 'form-control border-primary'}),
            # 'category': forms.Select(attrs={'class': 'form-control border-primary'}),
        }


class TriviaQuestionForm(forms.ModelForm):

    class Meta:
        model = TriviaQuestion
        fields = [ 'label', 'order',]
        labels = {
            'label':'Question'
        }

        widgets = {
            'label':forms.TextInput(attrs={'class':'form-control border-primary'}),
            'order':forms.TextInput(attrs={'class':'form-control border-primary'}),
        }


class TriviaOptionForm(forms.ModelForm):

    class Meta:
        model = TriviaAnswer
        fields = [ 'text', 'is_correct',]
        labels = {
            'text':'Option'
        }

        widgets = {
            'text':forms.TextInput(attrs={'class':'form-control border-primary'}),
        }

frontend/templates/frontend/add_student.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %} Student Form {% endblock %}
{% block css_vendors %}
    <link rel="stylesheet" type="text/css"
          href="{% static 'app-assets/vendors/css/tables/datatable/datatables.min.css' %}">
    <link rel="stylesheet" type="text/css"
          href="{% static 'app-assets/vendors/css/tables/extensions/responsive.dataTables.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/vendors/css/ui/jquery-ui.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/css/plugins/ui/jqueryui.css' %}">
    <style>
        #shoing_counter {
            width: 100%;
            margin-top: 17px;
            float: left;
            color: maroon;
            font-size: 1.5rem;
        }
    </style>
{% endblock %}
{% block css %}
    <style>
        .field_error li {
            color: red;
            list-style: none;
            text-align: right;
        }
    </style>
{% endblock %}
{% block content %}
    <section id="basic-form-layouts">
        <div class="row match-height">
            <div class="col col-md-2">.</div>
            <div class="col col-md-8 col-md-offset-2">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title" id="basic-layout-colored-form-control">Form</h4>
                        <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                        <div class="heading-elements">

                        </div>
                    </div>
                    <div class="card-content collapse show">
                        <div class="card-body">

                            <div class="card-text">

                            </div>

                            <form class="form" method="post" novalidate>
                                {% csrf_token %}
                                <div class="form-body">
                                    {#                                    <h4 class="form-section"><i class="la la-eye"></i> About User</h4>#}
                                    <div class="row" style="padding-left: 15px; padding-right: 15px;">
                                        {% for field in form %}
                                            <div class="form-group" style="width: 100%;">
                                                <label>{{ field.label }}</label>
                                                {{ field }}
                                                <span class="field_error">{{ field.errors }}</span>
                                            </div>

                                        {% endfor %}

                                    </div>


                                </div>

                                <div class="form-actions right">

                                    <button type="submit" class="btn btn-primary">
                                        <i class="la la-check-square-o"></i> Save
                                    </button>
                                </div>
                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>


{% endblock %}


{% block js_vendor %}
    <script src="{% static 'app-assets/js/core/libraries/jquery_ui/jquery-ui.min.js' %}"></script>
{% endblock %}

{% block js %}
    <script src="{% static 'app-assets/vendors/js/tables/datatable/datatables.min.js' %}"></script>
    <script src="{% static 'app-assets/vendors/js/tables/datatable/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'app-assets/vendors/js/extensions/sweetalert.min.js' %}"></script>
    <script src="{% static 'app-assets/js/scripts/ui/jquery-ui/date-pickers.js' %}"></script>
    {#    <script src="{% static 'app-assets/js/scripts/tables/datatables-extensions/datatable-responsive.js' %}"></script>#}
    <script>


        $(document).ready(function () {

            $('#m_table_1').DataTable({
                {#scrollX: true#}
            });

        })



    </script>
{% endblock %}

frontend/templates/frontend/class_level.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %} Classes {% endblock %}
{% block css_vendors %}
    <link rel="stylesheet" type="text/css"
          href="{% static 'app-assets/vendors/css/tables/datatable/datatables.min.css' %}">
    <link rel="stylesheet" type="text/css"
          href="{% static 'app-assets/vendors/css/tables/extensions/responsive.dataTables.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/vendors/css/ui/jquery-ui.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'app-assets/css/plugins/ui/jqueryui.css' %}">
    <style>
        #shoing_counter {
            width: 100%;
            margin-top: 17px;
            float: left;
            color: maroon;
            font-size: 1.5rem;
        }
    </style>
{% endblock %}
{% block css %}
    <style>
        .field_error li {
            color: red;
            list-style: none;
            text-align: right;
        }
    </style>
{% endblock %}
{% block content %}
    <section id="basic-form-layouts">
        <div class="row match-height">
            <div class="col col-md-2">.</div>
            <div class="col col-md-8 col-md-offset-2">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title" id="basic-layout-colored-form-control">Form</h4>
                        <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                        <div class="heading-elements">

                        </div>
                    </div>
                    <div class="card-content collapse show">
                        <div class="card-body">

                            <div class="card-text">

                            </div>

                            <form class="form" method="post" novalidate>
                                {% csrf_token %}
                                <div class="form-body">
                                    {#                                    <h4 class="form-section"><i class="la la-eye"></i> About User</h4>#}
                                    <div class="row" style="padding-left: 15px; padding-right: 15px;">
                                        {% for field in form %}
                                            <div class="form-group" style="width: 100%;">
                                                <label>{{ field.label }}</label>
                                                {{ field }}
                                                <span class="field_error">{{ field.errors }}</span>
                                            </div>

                                        {% endfor %}

                                    </div>


                                </div>

                                <div class="form-actions right">

                                    <button type="submit" class="btn btn-primary">
                                        <i class="la la-check-square-o"></i> Save
                                    </button>
                                </div>
                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Alternative pagination table -->
    <section id="pagination">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Class List</h4>

                        <a class="heading-elements-toggle"><i class="la la-ellipsis-v font-medium-3"></i></a>
                        <div class="heading-elements">
                            <ul class="list-inline mb-0">
                                <li><a data-action="collapse"><i class="ft-minus"></i></a></li>
                                <li><a data-action="expand"><i class="ft-maximize"></i></a></li>
                            </ul>
                        </div>
                    </div>
                    <div class="card-content collapse show">
                        <div class="card-body card-dashboard">
                            <p class="card-text"></p>


                            <table class="table table-striped table-bordered alt-pagination responsive dataex-res-visibility"
                                   id="m_table_1">
                                <thead>
                                <tr>
                                    <th>SN</th>
                                    <th>Code</th>
                                    <th>Name</th>
                                    <th>No. of Students</th>
                                    <th>Action</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for obj in data %}
                                    <tr>
                                        <td>{{ forloop.counter }}</td>
                                        <td>{{ obj.code }}</td>
                                        <td>{{ obj.name }}</td>
                                        <td>{{ obj.student_set.all.count }}</td>

                                        <td>
                                            <div class="action">

                                                <a href="{% url 'class_level_list' obj.pk %}"><i
                                                        class="ft-edit text-success"></i></a>
{#                                                <form method="post" action="{% url 'crm:delete_member' member.pk %}"#}
{#                                                      id="del_mem_{{ member.pk }}"#}
{#                                                      style="display: inline">#}
{#                                                    {% csrf_token %}#}
{#                                                    <input type="hidden" name="member_delete_id"#}
{#                                                           value="{{ member.pk }} ">#}
{#                                                    <a onclick="delete_member('{{ member.pk }}')"><i#}
{#                                                            class="ft-trash-2 text-warning"></i></a>#}
{#                                                </form>#}


                                            </div>

                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                                <tfoot>
                                <tr>
                                    <th>SN</th>
                                    <th>Code</th>
                                    <th>Name</th>
                                    <th>No. of Students</th>
                                    <th>Action</th>
                                </tr>
                                </tfoot>
                            </table>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}


{% block js_vendor %}
    <script src="{% static 'app-assets/js/core/libraries/jquery_ui/jquery-ui.min.js' %}"></script>
{% endblock %}

{% block js %}
    <script src="{% static 'app-assets/vendors/js/tables/datatable/datatables.min.js' %}"></script>
    <script src="{% static 'app-assets/vendors/js/tables/datatable/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'app-assets/vendors/js/extensions/sweetalert.min.js' %}"></script>
    <script src="{% static 'app-assets/js/scripts/ui/jquery-ui/date-pickers.js' %}"></script>
    {#    <script src="{% static 'app-assets/js/scripts/tables/datatables-extensions/datatable-responsive.js' %}"></script>#}
    <script>


        $(document).ready(function () {

            $('#m_table_1').DataTable({
                {#scrollX: true#}
            });

        })



    </script>
{% endblock %}